// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hogwartsApi.Persistence.Contexts;

namespace hogwartsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210927191001_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("hogwartsApi.Domain.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasMaxLength(2)
                        .HasColumnType("INTEGER");

                    b.Property<byte>("House")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Identification")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Age = 19,
                            House = (byte)1,
                            Identification = 28441688L,
                            Lastname = "Alvarez",
                            Name = "Gabriel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
